version: 2
jobs:
  js-test:
    docker:
      - image: cimg/node:21.4.0
    steps:
      - checkout
      - run:
          name: Update npm
          command: |
            sudo npm install -g npm@latest
      - restore_cache:
          key: cf-dd1-{{ checksum "yarn.lock" }}
      - run:
          name: Install node dependencies
          command: |
            sudo npm install -g yarn --force
            yarn
      - save_cache:
          key: cf-dd1-{{ checksum "yarn.lock" }}
          paths:
            - "~/.cache"
      # - run:
      #     name: lint
      #     command: |
      #       yarn run lint
      - run:
          name: build
          command: yarn run build
      - run:
          name: mocha tests
          command: |
            yarn run test
  python-test:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: Install python dependencies
          command: |
            curl -sSL https://install.python-poetry.org | python3 -
            poetry export --dev --without-hashes -f requirements.txt -o requirements.txt
            pip install --no-cache-dir -r requirements.txt --progress-bar off
      - run:
          name: run flake8
          command: |
            flake8 . --exclude=".venv/"
      - run:
          name: run isort
          command: |
            isort --check-only --diff --recursive --virtual-env ./.venv . --skip-glob=".venv"
      - run:
          name: run tests
          command: |
            pytest

workflows:
  version: 2
  build-and-test:
    jobs:
      - js-test
      - python-test
